---
name: merge_empty_pr
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: diff
        uses: KazukiHayase/review-git-diff-action@v1.0.0
        with:
          threshold: 0
          message: "⚠️  Git diff exceeds 0, won't be merged automatically."
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.TOKEN_APPROVE_PR }}
      - name: "Check Subject Is 'I pledge'"
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^I pledge(\n.*)*$'
          error: 'Subject too long (max 75)'
      - name: Check Body Line Length
        if: ${{ success() || failure() }}
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.+(\n.{0})*$'
          error: 'Body line too long (max 0)'
